In [2]:
import numpy as np

- Crie um array 6x6 preenchido com zero
- Preencha o centro desse array com um array 4x4 preenchido com 1
- Preencha o centro desse array com um array 4x4 preenchido com 2
- Gere um segundo array 6x6 com numeros inteiros aleatorios entre 0 e 2
- Subtraia o primeiro array pelo segundo


In [8]:
primeiro = np.zeros((6,6))
primeiro[1:-1,1:-1] = 1
primeiro[2:-2,2:-2] = 2
primeiro

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
segundo = np.random.randint(0,2,(6,6))
segundo

array([[0, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [14]:
primeiro - segundo

array([[ 0.,  0.,  0., -1., -1.,  0.],
       [-1.,  0.,  0.,  1.,  0.,  0.],
       [-1.,  1.,  1.,  1.,  0., -1.],
       [ 0.,  1.,  1.,  1.,  1., -1.],
       [ 0.,  0.,  1.,  1.,  0., -1.],
       [ 0., -1., -1., -1.,  0., -1.]])

- Crie um array 9x9 com numeros de 0 a 80 ordenados de modo crescente
- Selecione os números impares
- Selecione os números pares
- Selecione os múltiples de sete
- Seleciono os múltiplo de 10
- Selecione os números 32,33,42,43

In [19]:
array = np.arange(81).reshape(9,9)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [20]:
array[array % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79])

In [21]:
array[array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80])

In [22]:
array[array % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

In [33]:
array.diagonal()

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [39]:
np.union1d(array[3:4,5:7], array[4:5,6:8])

array([32, 33, 42, 43])

Criem um array com três dimensões, onde a primeira dimensão são os dias das semana, a segunda dimensão são as semanas do mês e a terceira são os meses do ano.
- Marque os finais de semmana com a letra W
- marque o começo do mês com a letra S
- Marque o Final do mês com a letra E
- Marque os demais dias com a letra D
- Marque os feriados com a letra F:
    - 1/1
    - 15/4
    - 24/4
    - 1/5
    - 7/9
    - 12/10
    - 2/11
    - 15/11
    - 25/12
1 - 7 = 0
8 -14 = 1
15 - 21 = 2
22 - 28 = 3

In [61]:
calendario = np.full([12,4,7],'')
calendario[:,:,5:] = 'W'
calendario[:,0,0] = 'S'
calendario[:,-1,-1] = 'E'
calendario[calendario == ''] = 'D'
calendario[0,0,0] = 'F'
calendario[3,2,0] = 'F'
calendario[3,3,2] = 'F'
calendario[4,0,0] = 'F'
calendario[8,0,6] = 'F'
calendario[9,1,4] = 'F'
calendario[10,0,1] = 'F'
calendario[10,2,0] = 'F'
calendario[11,3,3] = 'F'
calendario

array([[['F', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['F', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'F', 'D', 'D', 'W', 'E']],

       [['F', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
